import type { PlotData, Violation, Alert } from './types';

export const mockPlots: PlotData[] = [
  {
    id: 'PLT-2024-001',
    allotteeName: 'Apex Manufacturing Ltd.',
    allottedArea: 5000,
    currentArea: 5420,
    status: 'violation',
    complianceScore: 68,
    location: { lat: 28.6139, lng: 77.2090 },
    industryType: 'Manufacturing',
    allottedDate: '2020-03-15',
    lastInspection: '2026-01-10',
  },
  {
    id: 'PLT-2024-002',
    allotteeName: 'GreenTech Industries',
    allottedArea: 3500,
    currentArea: 3480,
    status: 'compliant',
    complianceScore: 95,
    location: { lat: 28.6100, lng: 77.2150 },
    industryType: 'Technology',
    allottedDate: '2019-08-20',
    lastInspection: '2026-02-01',
  },
  {
    id: 'PLT-2024-003',
    allotteeName: 'Industrial Metals Corp',
    allottedArea: 7200,
    currentArea: 7150,
    status: 'under-review',
    complianceScore: 82,
    location: { lat: 28.6200, lng: 77.2100 },
    industryType: 'Metals & Mining',
    allottedDate: '2021-01-10',
    lastInspection: '2026-01-28',
  },
  {
    id: 'PLT-2024-004',
    allotteeName: 'Vacant Plot',
    allottedArea: 4000,
    currentArea: 4000,
    status: 'vacant',
    complianceScore: 100,
    location: { lat: 28.6180, lng: 77.2200 },
    industryType: 'Unassigned',
    allottedDate: '2023-06-01',
    lastInspection: '2026-01-15',
  },
  {
    id: 'PLT-2024-005',
    allotteeName: 'PharmaTech Solutions',
    allottedArea: 4500,
    currentArea: 5100,
    status: 'violation',
    complianceScore: 62,
    location: { lat: 28.6120, lng: 77.2180 },
    industryType: 'Pharmaceutical',
    allottedDate: '2020-11-05',
    lastInspection: '2026-02-05',
  },
];

export const mockViolations: Violation[] = [
  {
    id: 'VIO-2024-045',
    plotId: 'PLT-2024-001',
    type: 'boundary-encroachment',
    severity: 'high',
    dateDetected: '2026-01-10',
    status: 'under-investigation',
    description: 'Plot boundary exceeded by 8.4% on eastern perimeter',
    deviationPercent: 8.4,
    industry: 'Apex Manufacturing Ltd.',
  },
  {
    id: 'VIO-2024-047',
    plotId: 'PLT-2024-005',
    type: 'unauthorized-construction',
    severity: 'critical',
    dateDetected: '2026-02-05',
    status: 'pending',
    description: 'Unauthorized warehouse construction detected via satellite imaging',
    deviationPercent: 13.3,
    industry: 'PharmaTech Solutions',
  },
  {
    id: 'VIO-2024-039',
    plotId: 'PLT-2024-003',
    type: 'land-use-change',
    severity: 'medium',
    dateDetected: '2026-01-28',
    status: 'under-investigation',
    description: 'Potential land-use modification detected - requires field inspection',
    industry: 'Industrial Metals Corp',
  },
  {
    id: 'VIO-2024-031',
    plotId: 'PLT-2023-089',
    type: 'environmental',
    severity: 'high',
    dateDetected: '2026-01-22',
    status: 'escalated',
    description: 'Environmental compliance breach - unauthorized waste disposal area',
    industry: 'Chemical Industries Ltd.',
  },
  {
    id: 'VIO-2024-028',
    plotId: 'PLT-2023-056',
    type: 'boundary-encroachment',
    severity: 'low',
    dateDetected: '2026-01-18',
    status: 'resolved',
    description: 'Minor boundary deviation corrected after inspection',
    deviationPercent: 2.1,
    industry: 'TechPark Developers',
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 'ALT-001',
    type: 'violation',
    severity: 'critical',
    title: 'Critical Violation Detected',
    description: 'PLT-2024-005: Unauthorized construction exceeding 13% of allotted area',
    timestamp: '2026-02-12T09:30:00',
    plotId: 'PLT-2024-005',
    isRead: false,
  },
  {
    id: 'ALT-002',
    type: 'compliance',
    severity: 'warning',
    title: 'Compliance Review Required',
    description: 'PLT-2024-003: Plot requires immediate field inspection',
    timestamp: '2026-02-12T08:15:00',
    plotId: 'PLT-2024-003',
    isRead: false,
  },
  {
    id: 'ALT-003',
    type: 'system',
    severity: 'info',
    title: 'Satellite Imagery Updated',
    description: 'New high-resolution imagery available for Sector 7-A',
    timestamp: '2026-02-12T07:00:00',
    isRead: true,
  },
  {
    id: 'ALT-004',
    type: 'risk',
    severity: 'warning',
    title: 'High-Risk Zone Identified',
    description: '3 plots in Sector 4-B showing compliance deterioration',
    timestamp: '2026-02-11T16:45:00',
    isRead: true,
  },
];

export const complianceTrendData = [
  { month: 'Aug', compliant: 142, violations: 12 },
  { month: 'Sep', compliant: 145, violations: 9 },
  { month: 'Oct', compliant: 148, violations: 11 },
  { month: 'Nov', compliant: 151, violations: 8 },
  { month: 'Dec', compliant: 147, violations: 14 },
  { month: 'Jan', compliant: 149, violations: 10 },
  { month: 'Feb', compliant: 152, violations: 7 },
];

export const violationsByTypeData = [
  { name: 'Boundary Encroachment', value: 45, color: '#FF6B6B' },
  { name: 'Unauthorized Construction', value: 28, color: '#FF922B' },
  { name: 'Land-use Change', value: 18, color: '#FAB005' },
  { name: 'Environmental', value: 9, color: '#8B5CF6' },
];
